### ISSUE TITLE
Add explanations of the various characteristics in the dropdowns (ie. Nitrogen mixed forms)

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/LIQWIDS#114] opened 2019-06-05 18:31 UTC
Came from user feedback.  I'm not sure where we would get this, maybe shawn could provide some text we could provide.

**Comment by kjacobsen16** [comment] 2019-06-05 18:54
duplicate of  https://github.com/USGS-WiM/LIQWIDS/issues/95

**Closed** 2019-06-05 18:54 UTC
